language: erlang

branches:
  only:
    - pharo

# build matrix: "PharoCore-1.3" or "Squeak4.3" ... parallel tests for
#   all listed environments
env:
   - ST=PharoCore-1.3

install:
   - sudo apt-get install -qq ia32-libs-multiarch
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script:
   - ./build.sh -i $ST -m -f "$PROJECT_HOME/tests/travisCI.st" -o travisCI
   - cd "${BUILD_PATH}/travisCI/"
   - ls -altr *
   - $BUILDER_CI_HOME/buildImageErrorCheck.sh
   - $BUILDER_CI_HOME/buildTravisStatusCheck.sh
#   - cat TravisTranscript.txt
